// <auto-generated />
using BulkOperations_EFCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkOperationsEFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkOperations_EFCore.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
